Models/ErrorViewModel.cs
namespace Spendify.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/ProductCategories.cs
using System.ComponentModel.DataAnnotations;

namespace Spendify.Models
{
    public class ProductCategories
    {
        public int Id { get; set; }
        [Required]
        [Display(Name="Product Category")]
        public string ProductCategory { get; set; }
    }
}

Areas/Admin/Controllers/ProductCategoriesController.cs
using Microsoft.AspNetCore.Mvc;
using Spendify.Data;
using Spendify.Models;

namespace Spendify.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ProductCategoriesController : Controller
    {
        private ApplicationDbContext _db;
        public ProductCategoriesController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
           // var data = _db.ProductCategories.ToList();
            return View(_db.ProductCategories.ToList());
        }

        // Create Get Action Method
        public ActionResult Create()
        {
            return View();
        }

        // Create Post Action Method
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ProductCategories productCategories)
        {
            if (ModelState.IsValid)
            {
                _db.ProductCategories.Add(productCategories);
                await _db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(productCategories);
        }

        // Edit Get Action Method
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var productCategory = _db.ProductCategories.Find(id);
            if (productCategory == null) 
            {
                return NotFound();
            }

            return View(productCategory);
        }

        // Edit Post Action Method
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(ProductCategories productCategories)
        {
            if (ModelState.IsValid)
            {
                _db.Update(productCategories);
                await _db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(productCategories);
        }

        // Details Get Action Method
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var productCategory = _db.ProductCategories.Find(id);
            if (productCategory == null)
            {
                return NotFound();
            }

            return View(productCategory);
        }

        // Details Post Action Method
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Details(ProductCategories productCategories)
        {
            return RedirectToAction(nameof(Index));
        }

        //GET Delete Action Method

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var productType = _db.ProductCategories.Find(id);
            if (productType == null)
            {
                return NotFound();
            }
            return View(productType);
        }

        //POST Delete Action Method

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int? id, ProductCategories productCategories)
        {
            if (id == null)
            {
                return NotFound();
            }

            if (id != productCategories.Id)
            {
                return NotFound();
            }

            var productType = _db.ProductCategories.Find(id);
            if (productType == null)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                _db.Remove(productType);
                await _db.SaveChangesAsync();
                TempData["delete"] = "Product type has been deleted";
                return RedirectToAction(nameof(Index));
            }

            return View(productCategories);
        }

    }
}

Areas/Customer/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Spendify.Models;
using System.Diagnostics;

namespace Spendify.Areas.Customer.Controllers
{
    [Area("Customer")]
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace Spendify.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Areas/Admin/Views/ProductCategories/Create.cshtml
@model Spendify.Models.ProductCategories;
@{
    ViewData["Title"] = "Create";
}

<h1>Create Product Category</h1>
<form asp-action="Create" method="post">
    <div class="p-4 rounded border">
        <div asp-validation-summary="ModelOnly" class="text-danger">
        </div>
        <div class="form-group row">
            <div class="col-2">
                <label asp-for="ProductCategory"></label>
            </div>
            <div class="col-5">
                <input asp-for="ProductCategory" class="form-control" />
            </div>
            <span asp-validation-for="ProductCategory" class="text-danger"></span>
        </div>
        <div class="form-group">
            <input type="submit" class="btn btn-primary" value="Save" />
            <a asp-action="Index" class="btn btn-success">Back to List</a>
        </div>
    </div>
</form>

@section Scripts{
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Areas/Admin/Views/ProductCategories/Delete.cshtml
@model Spendify.Models.ProductCategories;

@{
	ViewData["Title"] = "Delete";
}
<h2 class="text-info">Delete Product Category</h2>
<form asp-action="Delete" method="post">
    <div class="p-4 rounded border">
        <input type="hidden" asp-for="Id" />
        <div asp-validation-summary="ModelOnly" class="text-danger">
        </div>
        <div class="form-group row">
            <div class="col-2">
                <label asp-for="ProductCategory"></label>
            </div>
            <div class="col-5">
                <input asp-for="ProductCategory" readonly="readonly" class="form-control" />
            </div>
            <span asp-validation-for="ProductCategory" class="text-danger"></span>
        </div>
        <div class="form-group">
            <input type="submit" class="btn btn-danger" value="Delete" />
            <a asp-action="Index" class="btn btn-success">Back to List</a>
        </div>
    </div>
</form>

@section Scripts{
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Areas/Admin/Views/ProductCategories/Details.cshtml
@model Spendify.Models.ProductCategories;
@{
	ViewData["Title"] = "Details";
}

<h2>Product Type Details</h2>

<form asp-action="Details" method="post">
    <div class="p-4 rounded border">
        <div asp-validation-summary="ModelOnly" class="text-danger">

        </div>
        <div class="form-group row">
            <div class="col-2">
                <label asp-for="ProductCategory"></label>
            </div>
            <div class="col-5">
                <input asp-for="ProductCategory" readonly="readonly" class="form-control" />
            </div>
            <span asp-validation-for="ProductCategory" class="text-danger"></span>
        </div>
        <div class="form-group">

            <a asp-action="Edit" asp-route-id="@Model.Id" class="btn  btn-primary">Edit</a>
            <a asp-action="Index" class="btn btn-success">Back to List</a>
            @*<input type="submit" class="btn btn-success" value="Back to List" />*@
        </div>
    </div>
</form>

@section Scripts{
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Areas/Admin/Views/ProductCategories/Edit.cshtml
@model Spendify.Models.ProductCategories;
@{
	ViewData["Title"] = "Edit";
}

<h1>Edit Product Category</h1>
<form asp-action="Edit" method="post">
    <div class="p-4 rounded border">
        <input type="hidden" asp-for="Id"/>
        <div asp-validation-summary="ModelOnly" class="text-danger">
        </div>
        <div class="form-group row">
            <div class="col-2">
                <label asp-for="ProductCategory"></label>
            </div>
            <div class="col-5">
                <input asp-for="ProductCategory" class="form-control" />
            </div>
            <span asp-validation-for="ProductCategory" class="text-danger"></span>
        </div>
        <div class="form-group">
            <input type="submit" class="btn btn-primary" value="Update" />
            <a asp-action="Index" class="btn btn-success">Back to List</a>
        </div>
    </div>
</form>

@section Scripts{
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Areas/Admin/Views/ProductCategories/Index.cshtml
@using Spendify.Models;
@model IEnumerable<ProductCategories>

@{
}
    <br /><br />
    <div class="row">
        <div class="col-6">
            <h2 class="text-info">Product Categories</h2>
        </div>
        <div class="col-6 text-right">
            <a asp-action="Create" class="btn btn-info"><i class="fas fa-plus"></i>&nbsp; New Product Category</a>
        </div>
    </div>
    <br/>
    <div>
        <table class="table table-striped border">
            <tr class="table-info">
                <th>
                    @*@Html.DisplayNameFor(c=>c.ProductCategory)*@
                    Product Category 
                </th>
                <th></th>
                <th></th>
            </tr>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.ProductCategory</td>
                    <td>
                        <partial name="_ButtonPartial" model="@item.Id"/>
                    </td>
                </tr>
            }
        </table>
    </div>

Areas/Customer/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Home/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<div class="hero">
    <div class="hero-left">
        <img src="/imgs/left_img1.jpg"/>
    </div>
    <div class="hero-right">
        <img src="/imgs/right.jpg" />
    </div>
</div>

<div class="cards">
    <div class="card">
        <div class="card-img card-img1">
            <img src="/imgs/converse.png" alt="product image">
        </div>
        <div class="card-content">
            <h3 class="product-name">Converse</h3>
            <div class="price">$19.99</div>
        </div>
    </div>
    <div class="card">
        <div class="card-img card-img2">
            <img src="product.jpg" alt="product image">
        </div>
        <div class="card-content">
            <h3 class="product-name">Product Name</h3>
            <div class="price">$19.99</div>
        </div>
    </div>
    <div class="card">
        <div class="card-img card-img3">
            <img src="product.jpg" alt="product image">
        </div>
        <div class="card-content">
            <h3 class="product-name">Product Name</h3>
            <div class="price">$19.99</div>
        </div>
    </div>
</div>

Views/Shared/_ButtonPartial.cshtml
@model int
@{
}
<td style="width: 150px">
    <div class="btn-group">
        <a asp-action="Edit"  class="btn btn-primary" asp-route-id="@Model">
            <i class="far fa-edit"></i>
        </a>
        <a asp-action="Details" class="btn btn-success" asp-route-id="@Model"><i class="fas fa-list-ul"></i></a>
        <a asp-action="Delete"  class="btn btn-danger" asp-route-id="@Model">
            <i class="fas fa-trash-alt"></i>
        </a>
    </div>
</td>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Spendify</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Spendify.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css" integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lato:wght@300;400;700&display=swap" rel="stylesheet">
</head>
<body>
        <section class ="wrapper">
            <header>
            <div class="header-top">

                <div class="top-container">

                    <ul class="header-social-container">

                        <li>
                            <a href="#" class="social-link">
                                <i class="fa-brands fa-facebook-f"></i>
                            </a>
                        </li>

                        <li>
                            <a href="#" class="social-link">
                                <i class="fa-brands fa-twitter"></i>
                            </a>
                        </li>

                        <li>
                            <a href="#" class="social-link">
                                <i class="fa-brands fa-instagram"></i>
                            </a>
                        </li>

                        <li>
                            <a href="#" class="social-link">
                                <i class="fa-brands fa-linkedin-in"></i>
                            </a>
                        </li>

                    </ul>

                    <div class="header-alert-news">
                        <p>
                            <b>Free Shipping</b>
                            This Week Order Over - $55
                        </p>
                    </div>

                    <div class="header-top-actions">

                        <select name="currency">

                            <option value="usd">USD &dollar;</option>
                            <option value="eur">EUR &euro;</option>

                        </select>

                        <select name="language">

                            <option value="en-US">English</option>
                            <option value="es-ES">Espa&ntilde;ol</option>
                            <option value="fr">Fran&ccedil;ais</option>

                        </select>

                    </div>

                </div>

            </div>

                <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
                    <div class="container-fluid">
                        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Spendify</a>
                        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                                aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                        <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                            <ul class="navbar-nav flex-grow-1">
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="Admin" asp-controller="ProductCategories" asp-action="Index">Product Category</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                                </li>
                            </ul>
                            <partial name="_LoginPartial" />
                        </div>
                    </div>
                </nav>
            </header>
            <div class="container">
                <main role="main" class="pb-3">
                    @RenderBody()
                </main>
            </div>

            @*<footer class="border-top footer text-muted">
                <div class="container">
                    &copy; 2023 - Spendify - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                </div>
            </footer>*@
        </section>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>